defaultPortal: DevTestv1
portals:
  - name: DevTestv1
    portalId: 48715351
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COH794z6MhIpQlNQMl8kQEwrAhwACAkCARMXAQEBAgECAQIBDQMKAQIDBxsBAQEBQgEY16ydFyCDnbcdKO7pDDIUBuHSb6vkgSgd98xheLxhZnz9MHs6VkJTUDJfJEBMKwJJAAgTBgYdAQEBUSscAQEBAQ8BAQQFAQEBAQQBBQEBAQgBBgIDARAEDwEIBAEBAQEBBAEFARIJAwExAQEBBAEBAQEBAQEBQQEHWhoBQhSCwBtquAT7nftldDLh24P_1ooe8koDbmExUgBaAGABaABwAA
        expiresAt: '2025-06-24T11:06:15.435Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRuYTEtMDdmOS02OTM0LTQxNzktOWM2ZC1hZmZlMThhYzFhMWYQ16ydFxiDnbcdKhkABeaRgmFHkuHgpSqAV3TY8eIuOo9U7JJ1SgNuYTE
    parentAccountId: 45986199
