defaultPortal: DevTestv1
portals:
  - name: DevTestv1
    portalId: 48715351
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJ3Xm5D6MhIpQlNQMl8kQEwrAhwACAkCARMXAQEBAgECAQIBDQMKAQIDBxsBAQEBQgEY16ydFyCDnbcdKO7pDDIUBnQxYFwhi3-HArFAXl6pXze5Oho6VkJTUDJfJEBMKwJJAAgTBgYdAQEBUSscAQEBAQ8BAQQFAQEBAQQBBQEBAQgBBgIDARAEDwEIBAEBAQEBBAEFARIJAwExAQEBBAEBAQEBAQEBQQEHWhoBQhR7hvPnlLLSGAbW_ukljRLVp0iPzUoDbmExUgBaAGABaABwAA
        expiresAt: '2025-06-24T13:00:52.039Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRuYTEtMDdmOS02OTM0LTQxNzktOWM2ZC1hZmZlMThhYzFhMWYQ16ydFxiDnbcdKhkABeaRgmFHkuHgpSqAV3TY8eIuOo9U7JJ1SgNuYTE
    parentAccountId: 45986199
